# Generated by Django 4.2.13 on 2024-06-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Project',
        ),
    ]
